### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hecerinc** [melytc/cadhac#2]

**Comment by hecerinc** [comment]
<img width="1520" alt="footercadhacartboard 2 2x" src="https://user-images.githubusercontent.com/7988472/39098648-98c57262-4633-11e8-8519-0e040df6d3ea.png">
@melytc wdyathink?

**Comment by melytc** [comment]
I like it a lot!
También creo que tienen cuenta de YouTube con sus videos, por si se puede agregar el logo también :)
Al menos yo si stalkeo quienes ponen YT jajajaja

**Comment by hecerinc** [comment]
Kewl 😀  bueno si quieres se lo agregas en el código
