### ISSUE TITLE
About us - Load content

### ISSUE THREAD

**Issue by melytc** [melytc/cadhac#24]

**Comment by melytc** [comment]
Done in daf0a478c928748e3bcb00a50d44aa8a7ed9fe72

**Comment by hecerinc** [comment]
Also hay que cambiar el banner

**Comment by melytc** [comment]
Changed in  c7bf2e9.

Te parece?
![screenshot-2018-4-23 cadhac](https://user-images.githubusercontent.com/8518253/39150985-9e9e05c4-4709-11e8-8eca-0f3e2645e248.jpg)

**Comment by melytc** [comment]
No sé si se verá mejor si le quitamos el fondo gris de los reconocimientos. 🧐
