### ISSUE TITLE
Sobre nosotros: fix

### ISSUE THREAD

**Issue by melytc** [melytc/cadhac#38]
En el banner, ajustar la imagen para que se vean las caras.

Sección de reconocimientos: 
- agregar funcionalidad de hide/show a los botones (círculos). 
- Quitar el subrayado (text-decoration: none en los títulos) (wdythink?)

Quienes somos -> Areas (validar diseño)

**Comment by hecerinc** [comment]
El subrayado es un affordance para que la genta sepa que es un clickable item. Si no lo ponemos creo que la gente no va a saber que es un link
