### ISSUE TITLE
Ya que andas en eso, me ayudas a abrir estos?

### ISSUE THREAD

**Issue by hecerinc** [melytc/cadhac#41]
## Home

Politica de privacidad
Newsletter
Fotos banner cortarlas
Links grid

## Comunicados

- Buscador

## Sobre nosotros

- Quienes somos -> Areas (validar diseño)

## Publicaciones

- Banner img
- Banner title -> match titulo del informe

## Desaparecidos

- Edna

## Contacto

cadhac@cadhac.org

Atencion a casos: Lu-Vie 9AM a 1PM

**Comment by hecerinc** [comment]
:D pretty please

**Comment by melytc** [comment]
https://gph.is/1K01alI

**Comment by melytc** [comment]
Yes sir
https://giphy.com/gifs/T8Dhl1KPyzRqU/html5

**Comment by melytc** [comment]
Done :) closing this one.
